application:
  name: sample-app
 
services:
 
  - name: frontend
    replicas: 2
    healthCheck: true
    resources: true
    autoscaling: true
    pdbEnabled: true
    chaosTested: true
    tlsEnabled: true
    monitoring: true
    logging: true
    tracing: true
    circuitBreaker: true
 
  - name: backend
    replicas: 2
    healthCheck: true
    resources: true
    autoscaling: true
    pdbEnabled: true
    chaosTested: true
    tlsEnabled: true
    monitoring: true
    logging: true
    tracing: true
    circuitBreaker: true
 
  - name: database
    replicas: 2
    backupEnabled: true
    resources: true
    monitoring: true
    logging: true