apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-demo-app
  namespace: resilience
 
spec:
  replicas: 3
 
  selector:
    matchLabels:
      app: sample-demo-app
 
  template:
    metadata:
      labels:
        app: sample-demo-app
        chaos-target: "true"
 
    spec:
      containers:
      - name: sample-demo-app
        image: sample-demo-app:latest